# Change these first
owner: jorgechato
repo: status.jrg.tools

sites:
  - name: Short URL
    url: https://x.jrg.tools/list?size=0

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.jrg.tools
  # baseUrl: /your-repo-name
  logoUrl: https://avatars.githubusercontent.com/u/4450555?v=4
  name: JRG Tools
  introTitle: "**JRG Tools**"
  introMessage:  Uptime monitor and status page for all of my tools.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
