owner: jorgechato
repo: status.jrg.tools

sites:
  - name: X - Short URL
    url: https://x.jrg.tools/health
  - name: Where is Jorge Today?
    url: https://whereisjorge.today/
  - name: What is Jorge doing Today?
    url: https://what.jorgechato.com/
  - name: "Jorge Chato's page"
    url: https://jorgechato.com/

assignees:
  - jorgechato

status-website:
  themeUrl: https://status.jrg.tools/custom-light.css
  cname: status.jrg.tools
  logoUrl: https://avatars.githubusercontent.com/u/4450555?v=4
  name: JRG Tools
  navbar:
    - title: Status
      href: /
    - title: Github
      href: https://github.com/jorgechato/
  favicon: https://jorgechato.com/favicon.ico

i18n:
  footer: This page is [open source]($REPO), powered by Upptime.
